// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package data

import (
	"database/sql"
	"time"
)

type Icon struct {
	OwnerID     int64     `json:"owner_id"`
	LinkID      int64     `json:"link_id"`
	CreatedAt   time.Time `json:"created_at"`
	ContentType string    `json:"content_type"`
	Data        []byte    `json:"data"`
}

type Link struct {
	ID        int64     `json:"id"`
	OwnerID   int64     `json:"owner_id"`
	CreatedAt time.Time `json:"created_at"`
	Url       string    `json:"url"`
	Name      string    `json:"name"`
	Clicked   int64     `json:"clicked"`
	LogoUrl   string    `json:"logo_url"`
}

type Owner struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	LastUsed  time.Time `json:"last_used"`
	Name      string    `json:"name"`
}

type PullRequest struct {
	ID          int64          `json:"id"`
	OwnerID     int64          `json:"owner_id"`
	CreatedAt   time.Time      `json:"created_at"`
	Number      int64          `json:"number"`
	Repo        string         `json:"repo"`
	Url         string         `json:"url"`
	Description string         `json:"description"`
	Commitid    sql.NullString `json:"commitid"`
}

type PullRequestIgnore struct {
	ID        int64     `json:"id"`
	OwnerID   int64     `json:"owner_id"`
	CreatedAt time.Time `json:"created_at"`
	Number    int64     `json:"number"`
	Repo      string    `json:"repo"`
}

type WatchItem struct {
	ID        int64     `json:"id"`
	OwnerID   int64     `json:"owner_id"`
	CreatedAt time.Time `json:"created_at"`
	Name      string    `json:"name"`
	Repo      string    `json:"repo"`
}
